-- Seed data for the report-v2 economic calendar: 2026-07
-- Generated by scripts\New-EconomicEventsSeed.ps1. Run after db/economic_events.sql.
--
-- Fill in the rows below, then run this file in the Supabase SQL editor.
-- Columns: event_date, event_time, region(KR/US/...), title, importance(high/medium/low/holiday), actual, forecast, source.
-- Re-running is safe: existing (event_date, region, title) rows are updated, not duplicated.

insert into public.economic_events (
  event_date,
  event_time,
  region,
  title,
  importance,
  actual,
  forecast,
  source
) values
  -- TODO: replace the example row with this month's events, comma-separated.
  ('2026-07-15', '21:30', 'US', '소비자물가지수', 'high', null, null, 'manual_seed')
on conflict (event_date, region, title) do update set
  event_time = excluded.event_time,
  importance = excluded.importance,
  actual = excluded.actual,
  forecast = excluded.forecast,
  source = excluded.source,
  updated_at = now();
