param(
    [int]$Year,
    [int]$Month,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

# Default to next month so the end-of-month routine needs no arguments.
if (-not $Year -or -not $Month) {
    $next = (Get-Date).AddMonths(1)
    if (-not $Year) { $Year = $next.Year }
    if (-not $Month) { $Month = $next.Month }
}

if ($Month -lt 1 -or $Month -gt 12) {
    throw "Month must be between 1 and 12."
}

$root = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
$fileName = "economic_events_seed_{0:D4}_{1:D2}.sql" -f $Year, $Month
$outPath = Join-Path $root "db\$fileName"

if ((Test-Path -LiteralPath $outPath) -and -not $Force) {
    throw "$fileName already exists. Use -Force to overwrite."
}

$monthLabel = "{0:D4}-{1:D2}" -f $Year, $Month
$exampleDate = "{0}-15" -f $monthLabel

$lines = @(
    "-- Seed data for the report-v2 economic calendar: $monthLabel",
    "-- Generated by scripts\New-EconomicEventsSeed.ps1. Run after db/economic_events.sql.",
    "--",
    "-- Fill in the rows below, then run this file in the Supabase SQL editor.",
    "-- Columns: event_date, event_time, region(KR/US/...), title, importance(high/medium/low/holiday), actual, forecast, source.",
    "-- Re-running is safe: existing (event_date, region, title) rows are updated, not duplicated.",
    "",
    "insert into public.economic_events (",
    "  event_date,",
    "  event_time,",
    "  region,",
    "  title,",
    "  importance,",
    "  actual,",
    "  forecast,",
    "  source",
    ") values",
    "  -- TODO: replace the example row with this month's events, comma-separated.",
    "  ('$exampleDate', '21:30', 'US', '소비자물가지수', 'high', null, null, 'manual_seed')",
    "on conflict (event_date, region, title) do update set",
    "  event_time = excluded.event_time,",
    "  importance = excluded.importance,",
    "  actual = excluded.actual,",
    "  forecast = excluded.forecast,",
    "  source = excluded.source,",
    "  updated_at = now();"
)

Set-Content -LiteralPath $outPath -Value ($lines -join "`n") -Encoding UTF8
Write-Host "Created $outPath"
Write-Host "Next: fill in the month's events, run the file in the Supabase SQL editor, then commit it."
